version: '2'
services:
  app:
    build: .
    ports:
      - "8080:8181"
    volumes:
      - .:/app
    env_file: .env
    working_dir: /app
    command: bash -c 'php artisan migrate && php artisan db:seed && php artisan serve --host=0.0.0.0 --port=8181'
    depends_on:
      - db
    links:
      - db
  db:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD={YOUR_PASSWORD}
      - MYSQL_DATABASE=laravelAuth
      - MYSQL_USER={{MYSQL_USER}}
      - MYSQL_PASSWORD={{MYSQL_PASSWORD}}
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: {{MYSQL_PASSWORD}}
